---
- edges:
  - 1
  - 2
  - 8
  - 13
  - 12
  - 7
  corners:
  - 4
  - 1
  - 5
  - 9
  - 13
  - 8
- edges:
  - 3
  - 4
  - 9
  - 15
  - 14
  - 8
  corners:
  - 5
  - 2
  - 6
  - 10
  - 14
  - 9
- edges:
  - 5
  - 6
  - 10
  - 17
  - 16
  - 9
  corners:
  - 6
  - 3
  - 7
  - 11
  - 15
  - 10
- edges:
  - 11
  - 12
  - 20
  - 26
  - 25
  - 19
  corners:
  - 12
  - 8
  - 13
  - 18
  - 23
  - 17
- edges:
  - 13
  - 14
  - 21
  - 28
  - 27
  - 20
  corners:
  - 13
  - 9
  - 14
  - 19
  - 24
  - 18
- edges:
  - 15
  - 16
  - 22
  - 30
  - 29
  - 21
  corners:
  - 14
  - 10
  - 15
  - 20
  - 25
  - 19
- edges:
  - 17
  - 18
  - 23
  - 32
  - 31
  - 22
  corners:
  - 15
  - 11
  - 16
  - 21
  - 26
  - 20
- edges:
  - 24
  - 25
  - 35
  - 41
  - 40
  - 34
  corners:
  - 22
  - 17
  - 23
  - 29
  - 34
  - 28
- edges:
  - 26
  - 27
  - 36
  - 43
  - 42
  - 35
  corners:
  - 23
  - 18
  - 24
  - 30
  - 35
  - 29
- edges:
  - 28
  - 29
  - 37
  - 45
  - 44
  - 36
  corners:
  - 24
  - 19
  - 25
  - 31
  - 36
  - 30
- edges:
  - 30
  - 31
  - 38
  - 47
  - 46
  - 37
  corners:
  - 25
  - 20
  - 26
  - 32
  - 37
  - 31
- edges:
  - 32
  - 33
  - 39
  - 49
  - 48
  - 38
  corners:
  - 26
  - 21
  - 27
  - 33
  - 38
  - 32
- edges:
  - 41
  - 42
  - 51
  - 56
  - 55
  - 50
  corners:
  - 34
  - 29
  - 35
  - 40
  - 44
  - 39
- edges:
  - 43
  - 44
  - 52
  - 58
  - 57
  - 51
  corners:
  - 35
  - 30
  - 36
  - 41
  - 45
  - 40
- edges:
  - 45
  - 46
  - 53
  - 60
  - 59
  - 52
  corners:
  - 36
  - 31
  - 37
  - 42
  - 46
  - 41
- edges:
  - 47
  - 48
  - 54
  - 62
  - 61
  - 53
  corners:
  - 37
  - 32
  - 38
  - 43
  - 47
  - 42
- edges:
  - 56
  - 57
  - 64
  - 68
  - 67
  - 63
  corners:
  - 44
  - 40
  - 45
  - 49
  - 52
  - 48
- edges:
  - 58
  - 59
  - 65
  - 70
  - 69
  - 64
  corners:
  - 45
  - 41
  - 46
  - 50
  - 53
  - 49
- edges:
  - 60
  - 61
  - 66
  - 72
  - 71
  - 65
  corners:
  - 46
  - 42
  - 47
  - 51
  - 54
  - 50
